// tslint:disable
/**
 * Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    Check,
    Group,
    Project,
} from '../models';

export interface StatusControllerReadChecksRequest {
    groupSlug: string;
    projectSlug: string;
}

export interface StatusControllerReadProjectsRequest {
    groupSlug: string;
}

/**
 * no description
 */
export class StatusApi extends BaseAPI {

    /**
     */
    statusControllerReadChecks({ groupSlug, projectSlug }: StatusControllerReadChecksRequest): Observable<Array<Check>>
    statusControllerReadChecks({ groupSlug, projectSlug }: StatusControllerReadChecksRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<Check>>>
    statusControllerReadChecks({ groupSlug, projectSlug }: StatusControllerReadChecksRequest, opts?: OperationOpts): Observable<Array<Check> | AjaxResponse<Array<Check>>> {
        throwIfNullOrUndefined(groupSlug, 'groupSlug', 'statusControllerReadChecks');
        throwIfNullOrUndefined(projectSlug, 'projectSlug', 'statusControllerReadChecks');

        return this.request<Array<Check>>({
            url: '/status/groups/{groupSlug}/projects/{projectSlug}/checks'.replace('{groupSlug}', encodeURI(groupSlug)).replace('{projectSlug}', encodeURI(projectSlug)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    statusControllerReadGroups(): Observable<Array<Group>>
    statusControllerReadGroups(opts?: OperationOpts): Observable<AjaxResponse<Array<Group>>>
    statusControllerReadGroups(opts?: OperationOpts): Observable<Array<Group> | AjaxResponse<Array<Group>>> {
        return this.request<Array<Group>>({
            url: '/status/groups',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    statusControllerReadProjects({ groupSlug }: StatusControllerReadProjectsRequest): Observable<Array<Project>>
    statusControllerReadProjects({ groupSlug }: StatusControllerReadProjectsRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<Project>>>
    statusControllerReadProjects({ groupSlug }: StatusControllerReadProjectsRequest, opts?: OperationOpts): Observable<Array<Project> | AjaxResponse<Array<Project>>> {
        throwIfNullOrUndefined(groupSlug, 'groupSlug', 'statusControllerReadProjects');

        return this.request<Array<Project>>({
            url: '/status/groups/{groupSlug}/projects'.replace('{groupSlug}', encodeURI(groupSlug)),
            method: 'GET',
        }, opts?.responseOpts);
    };

}
