// tslint:disable
/**
 * Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    StatusRecord,
} from '../models';

export interface StatusRecordControllerReadHistoryRequest {
    groupSlug: string;
    projectSlug: string;
    checkSlug: string;
}

/**
 * no description
 */
export class StatusRecordApi extends BaseAPI {

    /**
     */
    statusRecordControllerReadHistory({ groupSlug, projectSlug, checkSlug }: StatusRecordControllerReadHistoryRequest): Observable<Array<StatusRecord>>
    statusRecordControllerReadHistory({ groupSlug, projectSlug, checkSlug }: StatusRecordControllerReadHistoryRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<StatusRecord>>>
    statusRecordControllerReadHistory({ groupSlug, projectSlug, checkSlug }: StatusRecordControllerReadHistoryRequest, opts?: OperationOpts): Observable<Array<StatusRecord> | AjaxResponse<Array<StatusRecord>>> {
        throwIfNullOrUndefined(groupSlug, 'groupSlug', 'statusRecordControllerReadHistory');
        throwIfNullOrUndefined(projectSlug, 'projectSlug', 'statusRecordControllerReadHistory');
        throwIfNullOrUndefined(checkSlug, 'checkSlug', 'statusRecordControllerReadHistory');

        return this.request<Array<StatusRecord>>({
            url: '/groups/{groupSlug}/projects/{projectSlug}/checks/{checkSlug}'.replace('{groupSlug}', encodeURI(groupSlug)).replace('{projectSlug}', encodeURI(projectSlug)).replace('{checkSlug}', encodeURI(checkSlug)),
            method: 'GET',
        }, opts?.responseOpts);
    };

}
