// tslint:disable
/**
 * Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    StatusRecord,
} from '../models';

export interface StatusRecordControllerReadHistoryRequest {
    projectId: string;
    statusId: string;
}

/**
 * no description
 */
export class StatusRecordApi extends BaseAPI {

    /**
     */
    statusRecordControllerReadHistory({ projectId, statusId }: StatusRecordControllerReadHistoryRequest): Observable<Array<StatusRecord>>
    statusRecordControllerReadHistory({ projectId, statusId }: StatusRecordControllerReadHistoryRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<StatusRecord>>>
    statusRecordControllerReadHistory({ projectId, statusId }: StatusRecordControllerReadHistoryRequest, opts?: OperationOpts): Observable<Array<StatusRecord> | AjaxResponse<Array<StatusRecord>>> {
        throwIfNullOrUndefined(projectId, 'projectId', 'statusRecordControllerReadHistory');
        throwIfNullOrUndefined(statusId, 'statusId', 'statusRecordControllerReadHistory');

        return this.request<Array<StatusRecord>>({
            url: '/projects/{projectId}/status/{statusId}'.replace('{projectId}', encodeURI(projectId)).replace('{statusId}', encodeURI(statusId)),
            method: 'GET',
        }, opts?.responseOpts);
    };

}
