// tslint:disable
/**
 * Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface StatusRecord
 */
export interface StatusRecord {
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    groupSlug: string;
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    projectSlug: string;
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    checkSlug: string;
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    time: string;
    /**
     * @type {number}
     * @memberof StatusRecord
     */
    statusCode: number;
    /**
     * @type {number}
     * @memberof StatusRecord
     */
    latency: number;
    /**
     * @type {object}
     * @memberof StatusRecord
     */
    data: object;
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    _id: string;
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    uuid: string;
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    createdAt: string;
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    createdBy: string;
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    changedAt: string;
    /**
     * @type {string}
     * @memberof StatusRecord
     */
    changedBy: string;
}
